In [6]:
import xarray as xr
import xgboost as xgb
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_percentage_error, mean_absolute_error


def r2_score_multi(y_pred: np.ndarray, y_true: np.ndarray) -> float:
    """Calculated the r-squared score between 2 arrays of values

    :param y_pred: predicted array
    :param y_true: "truth" array
    :return: r-squared metric
    """
    return r2_score(y_pred.flatten(), y_true.flatten())

In [7]:
feat_list = ["137", "141", "144", "167", "182", "186", "187", "188", "228", "260048"]

targ_list = ["141", "144", "260048"]


In [8]:
base_req = {
    "class": "d1",
    "dataset": "climate-dt",
    "activity": "highresmip",
    "experiment": "cont",
    "generation": "1",
    "model": "ifs-nemo",
    "realization": "1",
    "expver": "0001",
    "stream": "clte",
    "resolution": "high",
    "type": "fc",
    "levtype": "sfc",
    "time": "0000/to/2300",
}


In [12]:
def add_time_location_to_request(start_date, end_date, point_locs):
    date_range = start_date + "/to/" + end_date
    base_req["date"] = date_range

    timeseries_feature = {
            "type" : "timeseries",
            "points": point_locs,
            "time_axis": "date",
        }
    
    base_req["feature"] = timeseries_feature

    return base_req


In [13]:
import earthkit.data

def extract_params(param_list, start_date, end_date, point_locs):
    param_str = "/".join(param_list)

    request = add_time_location_to_request(start_date, end_date, point_locs)

    request["param"] = param_str

    print(request)

    data = earthkit.data.from_source("polytope", "destination-earth", request, address="polytope.lumi.apps.dte.destination-earth.eu", stream=False)

    ds = data.to_xarray()

    return ds



In [26]:
training_start_date = "19900101"

training_end_date = "20020101"

training_loc = [(38, -9.5)]

feats_ds = extract_params(feat_list, training_start_date, training_end_date, training_loc)

target_ds = extract_params(targ_list, training_start_date, training_end_date, training_loc)

2025-10-24 10:53:07 - INFO - Key read from /Users/male/.polytopeapirc
2025-10-24 10:53:07 - INFO - Sending request...
{'request': 'activity: highresmip\n'
            'class: d1\n'
            'dataset: climate-dt\n'
            'date: 19900101/to/20020101\n'
            'experiment: cont\n'
            "expver: '0001'\n"
            'feature:\n'
            '  points:\n'
            '  - - 38\n'
            '    - -9.5\n'
            '  time_axis: date\n'
            '  type: timeseries\n'
            "generation: '1'\n"
            'levtype: sfc\n'
            'model: ifs-nemo\n'
            'param: 137/141/144/167/182/186/187/188/228/260048\n'
            "realization: '1'\n"
            'resolution: high\n'
            'stream: clte\n'
            'time: 0000/to/2300\n'
            'type: fc\n',
 'verb': 'retrieve'}
2025-10-24 10:53:07 - INFO - Polytope user key found in session cache for user male


{'class': 'd1', 'dataset': 'climate-dt', 'activity': 'highresmip', 'experiment': 'cont', 'generation': '1', 'model': 'ifs-nemo', 'realization': '1', 'expver': '0001', 'stream': 'clte', 'resolution': 'high', 'type': 'fc', 'levtype': 'sfc', 'time': '0000/to/2300', 'date': '19900101/to/20020101', 'feature': {'type': 'timeseries', 'points': [(38, -9.5)], 'time_axis': 'date'}, 'param': '137/141/144/167/182/186/187/188/228/260048'}


2025-10-24 10:53:09 - INFO - Request accepted. Please poll ./3af93c84-2da1-4d44-aa58-c2a77876b4b6 for status
2025-10-24 10:53:09 - INFO - Polytope user key found in session cache for user male
2025-10-24 10:53:09 - INFO - Checking request status (3af93c84-2da1-4d44-aa58-c2a77876b4b6)...
2025-10-24 10:53:09 - INFO - The current status of the request is 'queued'
2025-10-24 10:53:10 - INFO - The current status of the request is 'processing'
2025-10-24 10:57:07 - INFO - The current status of the request is 'processed'
2025-10-24 10:57:16 - INFO - Key read from /Users/male/.polytopeapirc                             
2025-10-24 10:57:16 - INFO - Sending request...
{'request': 'activity: highresmip\n'
            'class: d1\n'
            'dataset: climate-dt\n'
            'date: 19900101/to/20020101\n'
            'experiment: cont\n'
            "expver: '0001'\n"
            'feature:\n'
            '  points:\n'
            '  - - 38\n'
            '    - -9.5\n'
            '  time_axis

{'class': 'd1', 'dataset': 'climate-dt', 'activity': 'highresmip', 'experiment': 'cont', 'generation': '1', 'model': 'ifs-nemo', 'realization': '1', 'expver': '0001', 'stream': 'clte', 'resolution': 'high', 'type': 'fc', 'levtype': 'sfc', 'time': '0000/to/2300', 'date': '19900101/to/20020101', 'feature': {'type': 'timeseries', 'points': [(38, -9.5)], 'time_axis': 'date'}, 'param': '141/144/260048'}


2025-10-24 10:57:18 - INFO - Request accepted. Please poll ./7bbe1dd0-e722-4246-a227-a3038a495c41 for status
2025-10-24 10:57:18 - INFO - Polytope user key found in session cache for user male
2025-10-24 10:57:18 - INFO - Checking request status (7bbe1dd0-e722-4246-a227-a3038a495c41)...
2025-10-24 10:57:18 - INFO - The current status of the request is 'queued'
2025-10-24 10:57:19 - INFO - The current status of the request is 'processing'
2025-10-24 10:59:10 - INFO - The current status of the request is 'processed'


In [17]:
feats_ds

<xarray.Dataset> Size: 9MB
Dimensions:    (latitude: 1, longitude: 1, levelist: 1, number: 1, datetime: 1,
                t: 105216)
Coordinates:
  * latitude   (latitude) float64 8B 37.97
  * longitude  (longitude) float64 8B 350.5
  * levelist   (levelist) int64 8B 0
  * number     (number) int64 8B 0
  * datetime   (datetime) <U20 80B '2002-01-01 00:00:00Z'
  * t          (t) datetime64[ns] 842kB 1990-01-01 ... 2002-01-01T23:00:00
Data variables:
    tcwv       (latitude, longitude, levelist, number, datetime, t) float64 842kB ...
    sd         (latitude, longitude, levelist, number, datetime, t) float64 842kB ...
    sf         (latitude, longitude, levelist, number, datetime, t) float64 842kB ...
    2t         (latitude, longitude, levelist, number, datetime, t) float64 842kB ...
    e          (latitude, longitude, levelist, number, datetime, t) float64 842kB ...
    lcc        (latitude, longitude, levelist, number, datetime, t) float64 842kB ...
    mcc        (latitude, longitude, levelist, number, datetime, t) float64 842kB ...
    hcc        (latitude, longitude, levelist, number, datetime, t) float64 842kB ...
    tp         (latitude, longitude, levelist, number, datetime, t) float64 842kB ...
    tprate     (latitude, longitude, levelist, number, datetime, t) float64 842kB ...
Attributes: (12/14)
    activity:       highresmip
    class:          d1
    dataset:        climate-dt
    experiment:     cont
    expver:         0001
    generation:     1
    ...             ...
    realization:    1
    resolution:     high
    stream:         clte
    type:           fc
    number:         0
    Forecast date:  2002-01-01 00:00:00Z

In [18]:
target_ds

<xarray.Dataset> Size: 3MB
Dimensions:    (latitude: 1, longitude: 1, levelist: 1, number: 1, datetime: 1,
                t: 105216)
Coordinates:
  * latitude   (latitude) float64 8B 37.97
  * longitude  (longitude) float64 8B 350.5
  * levelist   (levelist) int64 8B 0
  * number     (number) int64 8B 0
  * datetime   (datetime) <U20 80B '2002-01-01 00:00:00Z'
  * t          (t) datetime64[ns] 842kB 1990-01-01 ... 2002-01-01T23:00:00
Data variables:
    sd         (latitude, longitude, levelist, number, datetime, t) float64 842kB ...
    sf         (latitude, longitude, levelist, number, datetime, t) float64 842kB ...
    tprate     (latitude, longitude, levelist, number, datetime, t) float64 842kB ...
Attributes: (12/14)
    activity:       highresmip
    class:          d1
    dataset:        climate-dt
    experiment:     cont
    expver:         0001
    generation:     1
    ...             ...
    realization:    1
    resolution:     high
    stream:         clte
    type:           fc
    number:         0
    Forecast date:  2002-01-01 00:00:00Z

In [ ]:
feats_ds_2 = feats_ds.isel(levelist=0).isel(datetime=0).isel(number=0).to_array().astype("float32").stack(z=("longitude", "latitude", "t")).transpose()

feats_ds_2

<xarray.DataArray (z: 105216, variable: 10)> Size: 4MB
array([[12.63741   ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [12.574942  ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [12.168167  ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 5.737132  ,  0.        ,  0.        , ...,  0.9472493 ,
         0.        ,  0.        ],
       [ 5.8311253 ,  0.        ,  0.        , ...,  0.9999871 ,
         0.        ,  0.        ],
       [ 7.3881836 ,  0.        ,  0.        , ...,  0.99999964,
         0.        ,  0.        ]], shape=(105216, 10), dtype=float32)
Coordinates:
    levelist   int64 8B 0
    number     int64 8B 0
    datetime   <U20 80B '2002-01-01 00:00:00Z'
  * variable   (variable) object 80B 'tcwv' 'sd' 'sf' ... 'hcc' 'tp' 'tprate'
  * z          (z) object 842kB MultiIndex
  * longitude  (z) float64 842kB 350.5 350.5 350.5 350.5 ... 350.5 350.5 350.5
  * latitude   (z) float64 842kB 37.97 37.97 37.97 37.97 ... 37.97 37.97 37.97
  * t          (z) datetime64[ns] 842kB 1990-01-01 ... 2002-01-01T23:00:00
Attributes: (12/14)
    activity:       highresmip
    class:          d1
    dataset:        climate-dt
    experiment:     cont
    expver:         0001
    generation:     1
    ...             ...
    realization:    1
    resolution:     high
    stream:         clte
    type:           fc
    number:         0
    Forecast date:  2002-01-01 00:00:00Z

In [38]:
target_ds_2 = target_ds.isel(levelist=0).isel(datetime=0).isel(number=0).to_array().astype("float32").stack(z=("longitude", "latitude", "t")).transpose() - feats_ds_2[:, [1,2,-1]].values

target_ds_2

<xarray.DataArray (z: 105216, variable: 3)> Size: 1MB
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       ...,
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], shape=(105216, 3), dtype=float32)
Coordinates:
    levelist   int64 8B 0
    number     int64 8B 0
    datetime   <U20 80B '2002-01-01 00:00:00Z'
  * variable   (variable) object 24B 'sd' 'sf' 'tprate'
  * z          (z) object 842kB MultiIndex
  * longitude  (z) float64 842kB 350.5 350.5 350.5 350.5 ... 350.5 350.5 350.5
  * latitude   (z) float64 842kB 37.97 37.97 37.97 37.97 ... 37.97 37.97 37.97
  * t          (z) datetime64[ns] 842kB 1990-01-01 ... 2002-01-01T23:00:00

In [ ]:
x = feats_ds_2.values
y = target_ds_2.values

# Setup the xgboost model instance and choose some parameters to control the training
model = xgb.XGBRegressor(
    n_estimators=128,
    tree_method="hist",
    objevtive=mean_absolute_error,
    # multi_strategy="multi_output_tree",
    # learning_rate=0.3,
    eval_metric=r2_score_multi,
    subsample=0.6,
)

print("Fitting XGB model...")
model.fit(x, y, eval_set=[(x, y)])

[[12.63741     0.          0.         ...  0.          0.
   0.        ]
 [12.574942    0.          0.         ...  0.          0.
   0.        ]
 [12.168167    0.          0.         ...  0.          0.
   0.        ]
 ...
 [ 5.737132    0.          0.         ...  0.9472493   0.
   0.        ]
 [ 5.8311253   0.          0.         ...  0.9999871   0.
   0.        ]
 [ 7.3881836   0.          0.         ...  0.99999964  0.
   0.        ]]
Fitting XGB model...
[0]	validation_0-rmse:0.00000	validation_0-r2_score_multi:1.00000
[1]	validation_0-rmse:0.00000	validation_0-r2_score_multi:1.00000
[2]	validation_0-rmse:0.00000	validation_0-r2_score_multi:1.00000
[3]	validation_0-rmse:0.00000	validation_0-r2_score_multi:1.00000
[4]	validation_0-rmse:0.00000	validation_0-r2_score_multi:1.00000
[5]	validation_0-rmse:0.00000	validation_0-r2_score_multi:1.00000
[6]	validation_0-rmse:0.00000	validation_0-r2_score_multi:1.00000
[7]	validation_0-rmse:0.00000	validation_0-r2_score_multi:1.00000
[8]	val

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False,
             eval_metric=<function r2_score_multi at 0x128806200>,
             feature_types=None, feature_weights=None, gamma=None,
             grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=128, n_jobs=None,
             num_parallel_tree=None, ...)

In [41]:
training_start_date = "20030101"

training_end_date = "20030102"

training_loc = [(38, -9.5)]

ds_test = extract_params(feat_list, training_start_date, training_end_date, training_loc)

2025-10-24 12:04:35 - INFO - Key read from /Users/male/.polytopeapirc
2025-10-24 12:04:35 - INFO - Sending request...
{'request': 'activity: highresmip\n'
            'class: d1\n'
            'dataset: climate-dt\n'
            'date: 20030101/to/20030102\n'
            'experiment: cont\n'
            "expver: '0001'\n"
            'feature:\n'
            '  points:\n'
            '  - - 38\n'
            '    - -9.5\n'
            '  time_axis: date\n'
            '  type: timeseries\n'
            "generation: '1'\n"
            'levtype: sfc\n'
            'model: ifs-nemo\n'
            'param: 137/141/144/167/182/186/187/188/228/260048\n'
            "realization: '1'\n"
            'resolution: high\n'
            'stream: clte\n'
            'time: 0000/to/2300\n'
            'type: fc\n',
 'verb': 'retrieve'}
2025-10-24 12:04:35 - INFO - Polytope user key found in session cache for user male


{'class': 'd1', 'dataset': 'climate-dt', 'activity': 'highresmip', 'experiment': 'cont', 'generation': '1', 'model': 'ifs-nemo', 'realization': '1', 'expver': '0001', 'stream': 'clte', 'resolution': 'high', 'type': 'fc', 'levtype': 'sfc', 'time': '0000/to/2300', 'date': '20030101/to/20030102', 'feature': {'type': 'timeseries', 'points': [(38, -9.5)], 'time_axis': 'date'}, 'param': '137/141/144/167/182/186/187/188/228/260048'}


2025-10-24 12:04:37 - INFO - Request accepted. Please poll ./160bd31c-aa4b-4ab0-877b-e584b9272b88 for status
2025-10-24 12:04:37 - INFO - Polytope user key found in session cache for user male
2025-10-24 12:04:37 - INFO - Checking request status (160bd31c-aa4b-4ab0-877b-e584b9272b88)...
2025-10-24 12:04:37 - INFO - The current status of the request is 'queued'
2025-10-24 12:04:39 - INFO - The current status of the request is 'processing'
2025-10-24 12:04:48 - INFO - The current status of the request is 'processed'


In [49]:
feats_test = ds_test.to_array().values.T

feats_test[[3]][0][0][0][0][0]

array([[ 4.94442040e+00,  0.00000000e+00,  0.00000000e+00,
         2.83625267e+02, -1.55916321e-04,  6.44326210e-04,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00]])

In [ ]:
model.predict(feats_test[[1]][0][0][0][0][0])

array([[0., 0., 0.]], dtype=float32)

In [50]:
for x in range(len(feats_test)-1):
    if x % 1000 == 0:
        print(f"on step{x}....")
    preds = model.predict(feats_test[[x]][0][0][0][0][0])
    

on step0....
